### ISSUE TITLE
A release with binary

### ISSUE THREAD

**Issue by Mygod** [meh2481/hrmTools#1]
Please?

**Comment by meh2481** [comment]
Just tried, and github is having issues with me uploading files in an actual release. No idea what's going on there, so here: https://dl.dropboxusercontent.com/u/31816885/programs/hrmDecompress.zip

**Comment by Mygod** [comment]
Umm... Try again?

**Comment by meh2481** [comment]
Looks to be an error with GitHub and Firefox. Added release from Chrome.
